### PR TITLE
Feature/system interface

### PR DESCRIPTION
**Pull request by tomtzook**
Implementation of proposal #63

### CODE REVIEW

**Comment by tomtzook** [comment]
@dandeduck the thing you suggested to change into.

**Comment by dandeduck** [comment]
> @dandeduck the thing you suggested to change into.

wow that's cool that it would be a thing, a lot of changes to do that tho

**Comment by tomtzook** [comment]
> > @dandeduck the thing you suggested to change into.
> 
> wow that's cool that it would be a thing, a lot of changes to do that tho

Not really, since it didn't require any framework changes. Just had to switch the classes which implemented systems.

**Comment by dandeduck** [comment]
> > > @dandeduck the thing you suggested to change into.
> > 
> > wow that's cool that it would be a thing, a lot of changes to do that tho
> 
> Not really, since it didn't require any framework changes. Just had to switch the classes which implemented systems.

I didn't go much into how you implemented it, you would have to explain it to me later so I could add it to Tracer

**Pull request closed without merging**
