### PR TITLE
Vision duck improvements

### PR DESCRIPTION
**Pull request by dandeduck**
The names and location of the new files is a placeholder, so up to you...

### CODE REVIEW

**Comment by dandeduck** [comment]
And yeah, I remember the `m` and first bland line conventions, I still didn't do it to your liking to show my disapproval of such practices.

**Review by tomtzook — COMMENTED** [review]
I see what you're trying to do, but this is soooo specific... Take a look at https://github.com/Flash3388/FRC-Vision-Template and https://github.com/Flash3388/FRC-Vision-Template/blob/master/src/main/java/frc/team3388/vision/user/UserProcessor.java

**Comment by tomtzook** [comment]
> I see what you're trying to do, but this is soooo specific... Take a look at https://github.com/Flash3388/FRC-Vision-Template and https://github.com/Flash3388/FRC-Vision-Template/blob/master/src/main/java/frc/team3388/vision/user/UserProcessor.java

Perhaps this covers what you are looking for.

**Comment by dandeduck** [comment]
> I see what you're trying to do, but this is soooo specific... Take a look at https://github.com/Flash3388/FRC-Vision-Template and https://github.com/Flash3388/FRC-Vision-Template/blob/master/src/main/java/frc/team3388/vision/user/UserProcessor.java

God damn it why did you tell me to do if it's already a thing?????

**Comment by dandeduck** [comment]
The template is literally what I was looking for omg what a waste

**Comment by tomtzook** [comment]
> > I see what you're trying to do, but this is soooo specific... Take a look at https://github.com/Flash3388/FRC-Vision-Template and https://github.com/Flash3388/FRC-Vision-Template/blob/master/src/main/java/frc/team3388/vision/user/UserProcessor.java
> 
> God damn it why did you tell me to do if it's already a thing?????

You said you wanted to do something with vision, you never specified what it was.
You might want to take a look at [`vision communication from robot example`](https://github.com/Flash3388/FlashFRC/tree/development/examples/vision/robot-nt-vision/src/main/java/frc/team3388/robot) .

So just close this? Or do you still want to add this?

**Comment by dandeduck** [comment]
> > > I see what you're trying to do, but this is soooo specific... Take a look at https://github.com/Flash3388/FRC-Vision-Template and https://github.com/Flash3388/FRC-Vision-Template/blob/master/src/main/java/frc/team3388/vision/user/UserProcessor.java
> > 
> > God damn it why did you tell me to do if it's already a thing?????
> 
> You said you wanted to do something with vision, you never specified what it was.
> You might want to take a look at [`vision communication from robot example`](https://github.com/Flash3388/FlashFRC/tree/development/examples/vision/robot-nt-vision/src/main/java/frc/team3388/robot) .
> 
> So just close this? Or do you still want to add this?

Take a look at the conversation in WhatsApp, I specifically said that "it's too complicated for the new guys" and you said "go ahead". I don't  care, you decide

**Comment by tomtzook** [comment]
I guess I should have shown you the changes earlier.

Won't do.

**Pull request closed without merging**
